name: CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SINGLESTORE_PASS: ${{ secrets.SINGLESTORE_PASS }}
      SINGLESTORE_USER: ${{ secrets.SINGLESTORE_USER }}
      SINGLESTORE_HOST: ${{ secrets.SINGLESTORE_HOST }}
      SINGLESTORE_PORT: ${{ secrets.SINGLESTORE_PORT }}
      SINGLESTORE_DB_NAME: ${{ secrets.SINGLESTORE_DB_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Create .env from secrets
        run: |
          cat <<EOF > .env
          SINGLESTORE_PASS=${{ secrets.SINGLESTORE_PASS }}
          SINGLESTORE_USER=${{ secrets.SINGLESTORE_USER }}
          SINGLESTORE_HOST=${{ secrets.SINGLESTORE_HOST }}
          SINGLESTORE_PORT=${{ secrets.SINGLESTORE_PORT }}
          SINGLESTORE_DB_NAME=${{ secrets.SINGLESTORE_DB_NAME }}
          EOF

      - name: Copy .env.example files
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint
