name: CI

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SINGLESTORE_PASS: ${{ secrets.SINGLESTORE_PASS }}
      SINGLESTORE_USER: ${{ secrets.SINGLESTORE_USER }}
      SINGLESTORE_HOST: ${{ secrets.SINGLESTORE_HOST }}
      SINGLESTORE_PORT: ${{ secrets.SINGLESTORE_PORT }}
      SINGLESTORE_DB_NAME: ${{ secrets.SINGLESTORE_DB_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Create .env from secrets
        run: |
          cat <<EOF > .env
          SINGLESTORE_PASS=${{ secrets.SINGLESTORE_PASS }}
          SINGLESTORE_USER=${{ secrets.SINGLESTORE_USER }}
          SINGLESTORE_HOST=${{ secrets.SINGLESTORE_HOST }}
          SINGLESTORE_PORT=${{ secrets.SINGLESTORE_PORT }}
          SINGLESTORE_DB_NAME=${{ secrets.SINGLESTORE_DB_NAME }}
          testing=${{ secrets.testing }}
          EOF
      - name: List Git configuration
        run: git config --list
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump env context
        run: echo '${{ toJSON(env) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Display .env contents # <-- Add this step
        run: cat .env

      - name: Debug variable
        run: echo "The value of MY_VAR is ${{ env.MY_VAR }}"
        
      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint
